[package]
name = "decrypt"
version = "0.1.0"
authors = ["Coccifixio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6"
enquirer = "0.4"
regex = "1.3"
iter-set = "2"
